config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :rankings
  resources :courses
  resources :institutions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
    extend ActiveSupport::Concern

    module ClassMethods
        def filter(filtering_params)
            results = self.where(nil)

            filtering_params.each do |key, value|
                results = results.public_send(key, value) if value.present?
            end
            results
        end
    end
end
  

app/models/course.rb
class Course < ApplicationRecord
    has_many :rankings, dependent: :restrict_with_exception, :dependent => :destroy
    has_many :institutions, through: :rankings
    
    validates :name, presence: true
end

app/models/institution.rb
class Institution < ApplicationRecord
    has_many :rankings, dependent: :destroy
    has_many :courses, through: :rankings

    validates :name, presence: true
    validates :general_note, presence: true

    accepts_nested_attributes_for :rankings, allow_destroy: true
end

app/models/ranking.rb
class Ranking < ApplicationRecord
  include Filterable
  belongs_to :course
  belongs_to :institution

  validates :course, :institution, :student_score, :course_score, presence: true

  delegate :name, to: :course, prefix: true
  delegate :name, :general_note, to: :institution, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    render json: @institution
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)
    
    respond_to do |format|
      if @institution.save
        flash[:notice] = "Institution #{@institution.name} was created!."
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }

      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(
        :name, 
        :general_note,
        rankings_attributes: [
          :id,
          :course_id,
          :institution_id,
          :course_score,
          :student_score,
          :_destroy
        ])
    end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController 
    def index
        @rankings = rankings_query
        render json: @rankings
    end

    private
    
    def rankings_query
        RankingsQuery.new.relation
            .filter(
                params.slice(
                    :institution_id,
                    :course_id,
                    :institution_general_note,
                    :course_score,
                    :student_score
                )
            ).includes(:course, :institution)
            .joins(:institution)
            .order(Institution.arel_table[:general_note].desc)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home/index.html.erb
<h1 class="center-align">Enade Rank</h1>
<div id="home_content"></div>
<%= javascript_pack_tag 'home/entry'%>

app/views/institutions/_form.html.erb
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>
      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="row">
    <div id="insitution_form"></div>
  </div>
  
<% end %>

<script>
    window.institutionId = <%== institution.id.to_json %>;
</script>

<%= javascript_pack_tag 'institutions/entry'%>

app/views/institutions/edit.html.erb
<h1 class="center-align">Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>General note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.general_note %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>
<% unless notice.nil? %>
  <script> 
    M.toast({html: "<%= notice %>"})
  </script>
<% end %>

app/views/institutions/new.html.erb
<h1 class="center-align">New Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>General note:</strong>
  <%= @institution.general_note %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnadeRanking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render partial: "./layouts/shared/sidebar" %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/shared/_sidebar.html.erb
<ul id="slide-out" class="sidenav sidenav-fixed">
  <li><%= link_to  "Home", root_path %></li>
  <li><%= link_to  "Institutions", institutions_path %></li>
  <li><%= link_to  "Courses", courses_path %></li>
</ul>
<a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

<script>
  document.addEventListener('turbolinks:load', function() {
    M.Sidenav.init(document.getElementById('slide-out'));
  });
  document.addEventListener('turbolinks:before-visit', function() {
    instance = M.Sidenav.getInstance(document.getElementById('slide-out'));
    if (instance){
      instance.destroy();
    }
  });
</script>